#!/usr/bin/env bash

set -euo pipefail

essential="$HOME/.local/bin/c_formatter_42"

if [ ! -e "$essential" ]; then
	echo "Installing dependency (c_formatter_42)"

	pip3 install --break-system-packages c-formatter-42
	echo "Sucess"
	echo "Continuing..."
	sleep 2
fi

find . -type f \( -name "*.c" -o -name "*.h" \) -exec sh -c '
    for f; do
        tail -c1 "$f" | read -r _ || printf "\n" >> "$f"
    done
' _ {} +

find . -type f \( -name "*.c" -o -name "*.h" \) -exec sh -c '
    for f; do
	tmp=$(mktemp)
	python3 -m c_formatter_42 < "$f" > "$tmp"
	mv "$tmp" "$f"
    done
' _ {} +

norminette